package net.vheerden.archi.mcp.server;

import java.io.IOException;

import org.eclipse.equinox.security.storage.ISecurePreferences;
import org.eclipse.equinox.security.storage.SecurePreferencesFactory;
import org.eclipse.equinox.security.storage.StorageException;

/**
 * Persists the TLS keystore password in Equinox secure storage (TLS keystore audit finding).
 *
 * <p><b>Why secure storage, and why {@code getDefault()}.</b> The keystore password is a secret; it
 * must never sit in the plain {@code IPreferenceStore} (where {@code grep} of {@code .metadata} would
 * reveal it as cleartext). {@link SecurePreferencesFactory#getDefault()} returns the install's
 * <em>single shared</em> default secure storage — the SAME tree Archi itself and the bearer token
 * ({@link BearerTokenStore}) use. Our value is just one more entry in the SAME node
 * ({@value #NODE_PATH}) under a DISTINCT key ({@value #KEY_KEYSTORE_PASSWORD}, never colliding with
 * {@code BearerTokenStore.KEY_TOKEN = "authToken"}), so it reuses Archi's existing master password /
 * OS-keychain unlock with <em>no separate password and no second storage</em>. We deliberately never
 * call {@code open(customLocation, ...)} (that would spawn a separate storage with its own master
 * password). On macOS the {@code org.eclipse.equinox.security.macosx} fragment backs the master
 * password with the Keychain, so typically there is no prompt at all.</p>
 *
 * <p><b>Layering.</b> Mirrors {@link BearerTokenStore} and {@link CertificateGenerator}: a
 * {@code server/}-package helper the UI imports (no architecture-boundary breach — {@code server/}
 * has no UI dependency, and the UI already imports {@code server.BearerTokenStore} and
 * {@code server.CertificateGenerator}). Touches only JDK + the Equinox secure-storage API; no Jackson,
 * no EMF, no SWT.</p>
 *
 * <p><b>No {@code generate()}.</b> Unlike the bearer token, the keystore password is user-typed or
 * produced by {@link CertificateGenerator} — never randomly generated by this helper. This class only
 * stores, reads, and clears it.</p>
 *
 * <p><b>Fail behaviour.</b> When the secure store is unavailable or unreadable (a null
 * {@code getDefault()} in an odd headless context, a {@link StorageException}, a locked store) these
 * methods throw {@link KeystorePasswordStoreException} rather than returning a misleading {@code null}
 * — so callers can distinguish "no password set" from "could not read it" and fall back to the legacy
 * plain value without silently regressing TLS (see {@code McpPlugin.getKeystorePassword()}). The
 * password is <b>never logged</b> at any level, never put in an error message, never echoed to a
 * client.</p>
 */
public final class KeystorePasswordStore {

    /**
     * Secure-storage node path for this plugin's secrets — the SAME node as {@link BearerTokenStore}
     * (a node is just a namespace in the shared default storage, not a separate credential), so this
     * adds zero password ceremony.
     */
    static final String NODE_PATH = "/net/vheerden/archi/mcp";

    /**
     * Secure-storage key holding the keystore-password secret. Distinct from
     * {@code BearerTokenStore.KEY_TOKEN = "authToken"} so the two secrets never collide.
     */
    static final String KEY_KEYSTORE_PASSWORD = "keystorePassword";

    private KeystorePasswordStore() {
        // Utility class
    }

    /**
     * Reads the stored keystore password from secure storage.
     *
     * @return the password, or {@code null} if the store is reachable but no password has been set
     * @throws KeystorePasswordStoreException if secure storage is unavailable or cannot be read (so
     *         the caller can fall back to the legacy plain value rather than mistake an unreadable
     *         store for "no password")
     */
    public static String get() {
        try {
            return node().get(KEY_KEYSTORE_PASSWORD, null);
        } catch (StorageException e) {
            // Do NOT include the value in the message — only the failure.
            throw new KeystorePasswordStoreException("Failed to read keystore password from secure storage", e);
        }
    }

    /**
     * Persists (encrypted) the keystore password to secure storage and flushes it to disk so it is
     * durable immediately (even before the preference page's OK), then any later server start can read
     * it back.
     *
     * @param password the password to store (must be non-null/non-blank — callers type it or obtain
     *                 it from {@link CertificateGenerator})
     * @throws KeystorePasswordStoreException if secure storage is unavailable or the write/flush fails
     */
    public static void set(String password) {
        if (password == null || password.isBlank()) {
            throw new IllegalArgumentException("Refusing to store a null/blank keystore password");
        }
        try {
            ISecurePreferences node = node();
            node.put(KEY_KEYSTORE_PASSWORD, password, /* encrypt */ true);
            node.flush();
        } catch (StorageException | IOException e) {
            throw new KeystorePasswordStoreException("Failed to persist keystore password to secure storage", e);
        }
    }

    /**
     * Removes the stored keystore password. Used when the user clears the field; the read path
     * then falls back to the legacy plain value (which is empty post-migration).
     *
     * @throws KeystorePasswordStoreException if secure storage is unavailable or the flush fails
     */
    public static void clear() {
        try {
            ISecurePreferences node = node();
            node.remove(KEY_KEYSTORE_PASSWORD);
            node.flush();
        } catch (IOException e) {
            throw new KeystorePasswordStoreException("Failed to clear keystore password from secure storage", e);
        }
    }

    /**
     * Resolves this plugin's secure-storage node from the shared default storage.
     *
     * @return the node under {@value #NODE_PATH}
     * @throws KeystorePasswordStoreException if the default secure storage is unavailable
     *         ({@code getDefault()} returned {@code null} — e.g. headless with no provider)
     */
    private static ISecurePreferences node() {
        ISecurePreferences root = SecurePreferencesFactory.getDefault();
        if (root == null) {
            throw new KeystorePasswordStoreException(
                    "Equinox secure storage is unavailable (SecurePreferencesFactory.getDefault() returned null)");
        }
        return root.node(NODE_PATH);
    }

    /**
     * Thrown when secure storage is unavailable or an I/O/storage operation fails. Unchecked so the
     * helper stays a drop-in for the UI and the plugin read/migration paths; the read path translates
     * it into a legacy-plain fallback, the migration leaves the legacy value in place,
     * and the UI surfaces a clear error to the user. Never carries the password value in its message.
     *
     * <p>A sibling of {@code BearerTokenStore.BearerTokenStoreException} rather than a shared base
     * class, deliberately: the just-shipped/just-reviewed {@link BearerTokenStore} stays byte-identical
     * byte-identical.</p>
     */
    public static class KeystorePasswordStoreException extends RuntimeException {
        private static final long serialVersionUID = 1L;

        public KeystorePasswordStoreException(String message) {
            super(message);
        }

        public KeystorePasswordStoreException(String message, Throwable cause) {
            super(message, cause);
        }
    }
}
